version: '3.7'
services:
  ###############################################
  ########## external container #################
  ###############################################
  ########## LIA OVGU CONTAINERS #################
    testsample:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        -  ${LIA_AAS_RESTAPI_PORT_EXTERN}:${LIA_AAS_RESTAPI_PORT_INTERN}
      environment:
        -  REGISTRY_DATABASE_HOST=${LIA_MONGO_CONTAINER}
      volumes:
        - ./logs:/testsample/src/main/logs