version: '3.4'
services:
  fast-service:
    image: fraunhoferiosb/faaast-service
    volumes:
      - ../examples/:/app/resources/
    environment:
      - faaast_model=/app/resources/demoAAS.json
      - faaast_config=/app/resources/exampleConfiguration.json
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    external: true